### ISSUE TITLE
功能还没有完全开发完全

### ISSUE THREAD

**Issue by Dreamskya** [yangchong211/LifeHelper#1]
您好，我发现你项目很多功能，还没完善好的，不知道会不会继续完善，实现那些没开发好的功能，期待下一个版本学习。

**Comment by yangchong211** [comment]
会持续迭代的，会完善功能的。谢谢你的建议，

在 2017-12-27 21:27:07，"Dreamskya" <notifications@github.com> 写道：


您好，我发现你项目很多功能，还没完善好的，不知道会不会继续完善，实现那些没开发好的功能，期待下一个版本学习。

**Comment by Dreamskya** [comment]
期待。谢谢



zhangtao@simtoo.com
 
发件人： 潇湘剑雨
发送时间： 2017-12-28 10:20
收件人： yangchong211/LifeHelper
抄送： Dreamskya; Author
主题： Re: [yangchong211/LifeHelper] 功能还没有完全开发完全 (#1)
会持续迭代的，会完善功能的。谢谢你的建议，

在 2017-12-27 21:27:07，"Dreamskya" <notifications@github.com> 写道：


您好，我发现你项目很多功能，还没完善好的，不知道会不会继续完善，实现那些没开发好的功能，期待下一个版本学习。

**Comment by yangchong211** [comment]
嗯嗯，共同加油！

在 2017-12-28 14:18:35，"Dreamskya" <notifications@github.com> 写道：
期待。谢谢



zhangtao@simtoo.com

发件人： 潇湘剑雨
发送时间： 2017-12-28 10:20
收件人： yangchong211/LifeHelper
抄送： Dreamskya; Author
主题： Re: [yangchong211/LifeHelper] 功能还没有完全开发完全 (#1)
会持续迭代的，会完善功能的。谢谢你的建议，

在 2017-12-27 21:27:07，"Dreamskya" <notifications@github.com> 写道：


您好，我发现你项目很多功能，还没完善好的，不知道会不会继续完善，实现那些没开发好的功能，期待下一个版本学习。

**Comment by ksrainarthas** [comment]
希望功能更加完善

**Comment by yangchong211** [comment]
好的，多谢反馈，会慢慢继续完善的。只不过，这个是一年前的练手项目，添加的模块太多，后期会精简一下……
