### ISSUE TITLE
不知道下面这种情况有没有遇到过？

### ISSUE THREAD

**Issue by pardonhan** [yangchong211/LifeHelper#13]
我本机的gradle 版本是 3.3.1 
![22222](https://user-images.githubusercontent.com/11623810/53720458-c657b300-3e9b-11e9-9b2f-2fed3cc8f88a.png)

**Comment by yangchong211** [comment]
这个是kotlin语法黄色警告warning，不影响运行的。比如常量命名不规范，定义的变量或者方法没有用到就会报这种黄色警告，实际项目中warning是越少越好！
