### ISSUE TITLE
app安装后报错

### ISSUE THREAD

**Issue by mobileAiDev** [yangchong211/LifeHelper#14]
![企业微信截图_15522975839150](https://user-images.githubusercontent.com/37100939/54114527-996c4880-4425-11e9-9454-da09976d5889.png)

**Comment by mobileAiDev** [comment]
还是崩溃啊,一样的报错

**Comment by yangchong211** [comment]
报错日志：RealmException: 'class com.ns.yc.lifehelper.model.cache.CacheHomeNews' is not part of the schema for this Realm.
报错原因：realm与kotlin配置问题，组件化模式下
错误配置【参考方案：https://github.com/realm/realm-java/issues/3139】
```
apply plugin: 'com.android.application'
apply plugin: 'realm-android'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
```
正确配置【注意：realm-android要在kotlin配置之后】
```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'realm-android'
```
已经解决！
