### ISSUE TITLE
BaseAppManager 和 AppManager 区别

### ISSUE THREAD

**Issue by HannibalGR** [yangchong211/LifeHelper#2]
一个用在了BaseActivity 一个在BaseApplication  没弄明白区别 - -

**Comment by yangchong211** [comment]
本质上没有什么区别。都是处理activity容器的栈堆添加或者去除……
使用AppManager，则需要在BaseActivity中add或者remove处理栈堆，如果有activity没有继承BaseActivity，则需要单独处理。
使用BaseAppManager，则是利用Application.ActivityLifecycleCallbacks这个方法处理添加或者去除逻辑，这个方法是管理activity的生命周期……
